# Generated by Django 3.0.8 on 2020-07-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200718_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.DateField(auto_now=True),
        ),
    ]
