# Generated by Django 3.0.8 on 2020-07-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='employee',
            new_name='created_by',
        ),
    ]
